### PR TITLE
Started filling out .janno for Fischer_Gauls

### PR DESCRIPTION
**Pull request by Kavlahkaff**
Started filling out the .janno.

These are some columns where I was unsure:

1. In the haplogroups, they sometimes added a tilde or a ? at the end. I was not sure whether to keep or remove that.
2. They provide a Group_ID, which I used for the group_name column. Does this work as a group name or is this more like the collectionID/Alternative ID?
3. They provide locations e.g. France, Aude, Bessan "la Monédière". I then used the most exact region (i.e. Bessan) as Location since Location allows for only a single entry.  
4. They only say they used "osteological remains", is that enough information to put it into the source tissue column?

### CODE REVIEW

**Comment by stschiff** [comment]
Hi @Kavlahkaff, some quick replies:

1) Yes, please keep any tildes or symbols in the haplogroups. These typically have a meaning (which evades me, but can be important for the connoisseurs.
2) The group IDs I see in your PR look great. Would be good to have them for all samples. Not sure why they provide them only for some. If you can't fill these, just leave them empty for now and we see whether we can bring some expert in to help.
3) The location is only one entry, true, but it's free text, so feel free to enter something with commas. We really usually take whatever the authors say. 
4) Yes, for now that's OK. We were thinking about making this more systematic at some point, but for now that's fine.

Note that you can mark a PR as "draft" and then make it "ready for review" later to indicate that it's finalised from your side for now. Let us know whether it's finalised, then we can take a deeper look.

**Comment by stschiff** [comment]
Hi @Kavlahkaff, great. Some quick notes:
1) You have unnecessary quotations in some fields
2) I saw at least one wrong character in Location name "Buch�res"
3) The first sample has values "Latitude", "Longitude", "Date_Type" in the columns with the same name. Please check that no vertical shift in these columns has occurred.
4) Thanks for filling in `Date_BC_AD_*`, but are you sure that there is not a single C14-Radiocarbon date for these samples?
5) One sample has a numerical date-range entry in column `Date_Note`. What's going on there?
6) The first sample seems to have shifted values in `Nr_Libraries`, `Library_Names` and subsequent columns. Please check.

Did you have a chance to meet with @nevrome to get a primer on how to run `trident validate` yourself? I think this would help tremendously in preparing these Janno files.

**Comment by Kavlahkaff** [comment]
Hi @stschiff, thanks for the comment! I will have a look at the things you mentioned. I have not yet talked to @nevrome, but we have agreed to meeting some day next week to talk about how to use `trident validate`.

**Review by TCLamnidis — CHANGES_REQUESTED** [review]
The janno seems to have a line of whitespace at the end.

Beyond that, the updated janno has an additional column named `Column1`. I think the column might be empty all the way down?

As mentioned in #22, please do not overwrite any of the processing statistics produced by MINOTUAR. The RateX/Y columns in particular look off here, as they have values in E+13~E+14. The expected values for these are ~0-1.5

**Comment by TCLamnidis** [comment]
Ok, I realised the issue was that the original janno file from MINOTAUR had been overwritten in the original PR. I reverted that change and pulled the changes into this PR too

**Review by TCLamnidis — CHANGES_REQUESTED** [review]
OK, now the git changes look way cleaner. 

Please:
 - [x] revert the changes to the already-filled columns (`Rate*X/Y`, `Contamination*` etc)
 - [x] Remove `Column1`, but first check that the column is indeed empty and does not cause any column-wise shifts in the metadata.

**Comment by Kavlahkaff** [comment]
Hi @stschiff, @TCLamnidis, I have made the changes you requested and ran trident validate with no errors.

**Review by TCLamnidis — APPROVED** [review]
janno needs new line at EOF, but otherwise looks great! Thanks!

**Pull request merged**
