### PR TITLE
Add 2020_Bongers_SouthPeru

### PR DESCRIPTION
**Pull request by TCLamnidis**
Adds `2020_Bongers_SouthPeru`

Linked to https://github.com/poseidon-framework/minotaur-recipes/issues/6

`Longitude`, `Latitude` and `Genetic_Sex` columns are not filled in community archive. Filled here with information in paper supplementary Table found here:
https://www.pnas.org/doi/suppl/10.1073/pnas.2005965117/suppl_file/pnas.2005965117.sd01.xlsx

The supplementary table has also C14 dates, but they lack Lab codes. Also unclear if they are direct or contextual (given the community package has only contextual dates for the individuals.

### CODE REVIEW

**Comment by stschiff** [comment]
Great! Thanks for opening the PR. So, I took a look at the janno, looks really good and complete! The only column that I think we should still fill the "Site" column. Should I go ahead and look this up real quick and commit this right here, or is there a better process?

**Comment by TCLamnidis** [comment]
The supplementary table I linked above did not have a site. I will look into it, not too familiar with the publication. If you get to it before me, feel free to commit directly here, yes.

The package still needs to be bumped to v 1.0.0 once it's ready anyway

**Review by nevrome — APPROVED** [review]
Looks good to me :+1:

One minor observations: Some minotaur-archive packages now have an `Individual_ID` and some a `Main_ID`. I know that we haven't fully resolved this discussion (https://github.com/poseidon-framework/poseidon-schema/issues/74), but I'm curious what you're doing for the time being?

**Comment by TCLamnidis** [comment]
Currently using `Main_ID` https://github.com/poseidon-framework/poseidon-eager/blob/main/scripts%2Fpopulate_janno.py#L259

I think I changed some packages to Individual_ID manually after our discussions, but not consistently. Can always change that with a sed command for the whole archive.

**Comment by TCLamnidis** [comment]
@stschiff: I had a further look into the `Site` column. Indeed the supplement does not specify a Site. Additionally, the AADR has no Site for these individuals. 
Figure 1 gives some location names, but I'm not sure if those are actual Sites, or towns.
[Figure 1](https://www.pnas.org/cms/10.1073/pnas.2005965117/asset/600227ec-aa0b-4647-a22b-8b6551ed5b3f/assets/images/large/pnas.2005965117fig01.jpg)

**Comment by stschiff** [comment]
OK, maybe it's then actually OK to only fill the Location and leave site empty. I guess I was coming at it from a Pandora-Perspective, but I recall that `Site` perhaps isn't so central in Poseidon. So fine with leaving that empty!

**Review by stschiff — APPROVED** [review]

**Comment by TCLamnidis** [comment]
Ok. I'm merging this in for now. we can always update the jannos later if the information becomes clearer.

**Pull request merged**
